### ISSUE TITLE
No token accounts error - Snapshot Holders

### ISSUE THREAD

**Issue by k666-bit** [samuelvanderwaal/metaboss#83] opened 2022-02-11 12:12 UTC
Hi!

I just started getting this error today, whereas yesterday was working fine. Doesn't matter if you use the CMID or Update Authority

![image](https://user-images.githubusercontent.com/95923009/153589573-3e7b3be9-746d-4575-82f5-0f1dd5a5557e.png)

Any ideas? This happens for ALL accounts.

**Comment by samuelvanderwaal** [comment] 2022-02-11 17:08
Can you provide the full command you're running so I can try to duplicate the issue?

**Comment by k666-bit** [comment] 2022-02-11 18:03
> Can you provide the full command you're running so I can try to duplicate the issue?

metaboss -r https://ssc-dao.genesysgo.net snapshot holders --candy-machine-id EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP --v2

metaboss -r https://ssc-dao.genesysgo.net snapshot holders --update-authority God1GnHPzNrhWrbPTcv41YJAkra5GKQbqJkZuJeqkatZ --v2

**Comment by samuelvanderwaal** [comment] 2022-02-11 18:15
Those aren't candy machine ids: https://solscan.io/account/EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP

**Comment by samuelvanderwaal** [comment] 2022-02-11 18:22
`EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP` doesn't look like it's actually a candy machine id: https://solscan.io/account/EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP

> metaboss -r https://ssc-dao.genesysgo.net/ snapshot holders --update-authority God1GnHPzNrhWrbPTcv41YJAkra5GKQbqJkZuJeqkatZ --v2

The `--v2` flag is only for candy machine ids, not update authority.

**Comment by k666-bit** [comment] 2022-02-11 20:46
> `EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP` doesn't look like it's actually a candy machine id: https://solscan.io/account/EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP
> 
> > metaboss -r https://ssc-dao.genesysgo.net/ snapshot holders --update-authority God1GnHPzNrhWrbPTcv41YJAkra5GKQbqJkZuJeqkatZ --v2
> 
> The `--v2` flag is only for candy machine ids, not update authority.

I'm confused. That is the candy machine ID.

`{"program":{"uuid":"EUXHWU","candyMachine":"EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP"}`

I've been successfully snapshotting holders until today with the first command and it always worked correctly

**Comment by samuelvanderwaal** [comment] 2022-02-11 23:23
> EUXHWUyfFSXYuvei9oQxsVZ27H9iQN9WU1wKdwvRR3pP

Yeah, that's my bad, it is a candy machine ID. It wasn't showing up earlier when I looked it up. Not sure if I was doing something wrong or what was going on. I just tried the command on a different RPC and it worked so looks like the issue is with the GeneSysGo node and their new rate-limits. The error message is misleading, so I need to fix that.

**Comment by frosty214** [comment] 2022-02-11 23:51
Curious if this would have anything to do with this error I'm getting today?
![key](https://user-images.githubusercontent.com/87619885/153685883-fcb46cf4-c937-4a53-b00d-1a5282a6da22.JPG)

**Comment by samuelvanderwaal** [comment] 2022-02-12 00:04
@k666-bit update metaboss to 0.4.1 and it should work now

**Comment by samuelvanderwaal** [comment] 2022-02-12 00:04
> Curious if this would have anything to do with this error I'm getting today? ![key](https://user-images.githubusercontent.com/87619885/153685883-fcb46cf4-c937-4a53-b00d-1a5282a6da22.JPG)

It says `can't find key file` so make sure you're giving it the correct path to your key.

**Comment by frosty214** [comment] 2022-02-12 00:06
> > Curious if this would have anything to do with this error I'm getting today? ![key](https://user-images.githubusercontent.com/87619885/153685883-fcb46cf4-c937-4a53-b00d-1a5282a6da22.JPG)
> 
> It says `can't find key file` so make sure you're giving it the correct path to your key.

Yes, got that part just had to double check docs. It successfully ran, but returned `No unverified metadata for this creator and candy machine. Done!`. When I go to check my creator address for the NFT in Solscan, it still reads as unverified even 15 minutes later. Any ideas? 

Sorry if this isn't the best place to ask this question!

**Comment by samuelvanderwaal** [comment] 2022-02-12 00:07
> > > Curious if this would have anything to do with this error I'm getting today? ![key](https://user-images.githubusercontent.com/87619885/153685883-fcb46cf4-c937-4a53-b00d-1a5282a6da22.JPG)
> > 
> > 
> > It says `can't find key file` so make sure you're giving it the correct path to your key.
> 
> Yes, got that part just had to double check docs. It successfully ran, but returned `No unverified metadata for this creator and candy machine. Done!`. When I go to check my creator address for the NFT in Solscan, it still reads as unverified even 15 minutes later. Any ideas?
> 
> Sorry if this isn't the best place to ask this question!

Is your creator address the same one as the keypair?

**Comment by frosty214** [comment] 2022-02-12 00:09
It's not, how would that happen? I definitely didn't change it at any point somehow.

**Comment by samuelvanderwaal** [comment] 2022-02-12 00:09
> It's not, how would that happen? I definitely didn't change it at any point somehow.

You can only sign a creator with the creator keypair.

**Comment by k666-bit** [comment] 2022-02-16 11:40
> @k666-bit update metaboss to 0.4.1 and it should work now

This has fixed it :)

Thank you!

**Comment by samuelvanderwaal** [comment] 2022-02-16 17:20
Thanks for following up so I can close the issue! I appreciate it.

**Closed by samuelvanderwaal** 2022-02-16 17:20 UTC
