### ISSUE TITLE
Unable to update data in 0.6.0

### ISSUE THREAD

**Issue by nonfungible-dev** [samuelvanderwaal/metaboss#121] opened 2022-04-24 02:12 UTC
Hello! Long time user here, really appreciate the hard work you've put into this project. Thank you!

I'm writing because I appear to be unable to update my token data using v0.6.0 of metaboss.

```bash
  metaboss update data -l debug \
    -r [REDACTED] \
    -k [REDACTED] \
    -a $nft \
    -n data/$nft.json
```

Yields the following message:

```
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Failed to serialize or deserialize account data: Unknown
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]   3: Program log: Error: BorshIoError
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 8654 of 200000 compute units
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]   5: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Failed to serialize or deserialize account data: Unknown
[2022-04-24T01:51:28Z DEBUG solana_client::rpc_client]
```

Two things stand out to me here:

1. "Error processing Instruction 0: Failed to serialize or deserialize account data: Unknown"
2. "Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts"

My guess is that number 2 is causing number 1 by virtue of the fact that data is not being serialized due to the fact that updating metadata is deprecated?

Should I take the error message at face value and invoke a different method to update token data?

Any guidance you can provide would be much appreciated! Thank you again for your hard work!

**Comment by nonfungible-dev** [comment] 2022-04-24 02:23
Oh, and in case there's an issue with my data, here's an example of one of the data files I'm using with the above command:

```json
{
  "name": "Pesky Penguin #5691",
  "symbol": "NOOT",
  "uri": "https://arweave.net/oNtXDZsDdmfiXALe_vX-AsidurKuQd0ng45QLE7fxxU",
  "creators": [
    {
      "address": "A6XTVFiwGVsG6b6LsvQTGnV5LH3Pfa3qW3TGz8RjToLp",
      "verified": true,
      "share": 0
    },
    {
      "address": "pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k",
      "share": 40,
      "verified": true
    },
    {
      "address": "ppTeamTpw1cbC8ybJpppbnoL7xXD9froJNFb5uvoPvb",
      "share": 60,
      "verified": false
    }
  ],
  "update_authority": "pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k",
  "primary_sale_happened": true,
  "seller_fee_basis_points": 500
}```

**Comment by nonfungible-dev** [comment] 2022-04-24 02:42
It's probably worth adding that I started this whole exercise because the metaplex metadata on our tokens appears to be... wrong? It contains fields that I don't recognize that maybe shouldn't be there.

![image](https://user-images.githubusercontent.com/95830199/164953770-23133835-76ac-442f-bb21-342c3263297f.png)

I'm wondering if maybe this is at the root of all our issues? I figured updating the data account might solve these, but I wouldn't be surprised if we can't deserialize the existing data, and that's what's gumming up the works.

https://explorer.solana.com/address/CH4X6QQfRTaAFm2kGnqJEPoQrfoHa1cP2jcPm4Z7rjF/metadata

Thanks again for your time and any assistance you're able to provide!

**Comment by omarkilani** [comment] 2022-04-24 21:19
I'm helping @nonfungible-dev with this issue.

After talking to Blockiosaurus, they referenced this PR in metaplex-program-library:

https://github.com/metaplex-foundation/metaplex-program-library/pull/319

Which will fix this issue if/once deployed (?).

**Comment by samuelvanderwaal** [comment] 2022-04-25 05:23
@nonfungible-dev @omarkilani Sorry you're having this issue. It's not the deprecated function that's causing the problem (though that warning will go away next Metaboss version when I update to the `update_metadata_accounts_v2` handler). The issue is that some of the Pesky Penguins NFT data is corrupted in that it has data at the end of the struct that shouldn't be there and it's being interpreted by explorers as data for the new metadata fields in v1.1. We seen this with a few NFTs and that's what prompted my exploratory PR that Omar linked. 

It's not exactly clear why this happens. One idea is this might be caused by the creators array being updated to go from having more creators to less leaving extra data at the end of the struct due to the way Borshi serialization/deserialization works. However, that doesn't explain an NFT like [this one](https://solscan.io/token/DFR3KjTso6PFCyUtq48a2aPZQpMMoaFgtbdxtaLxF2TR#txs) that only has three txs and no update data tx. 

Ultimately, this needs to be solved at the Metaplex contract level as all the current handlers will fail to properly deserialize the data, so it can't be fixed by calling one of them to update the data. I'll bring this topic up again at the Metaplex engineering meeting tomorrow to see if we can assign some resources to fixing this.

**Comment by nonfungible-dev** [comment] 2022-04-25 12:02
Thanks for the details, @samuelvanderwaal!

The hypothesis about trailing data after a creators change makes sense; back in November 2021 we changed the creators array to consolidate royalties into a single "ppTeam" address.

I'm a little surprised we never noticed the corruption until now, especially because the creators change was the 2nd (of 5) changes we've made to our metadata, and none of the other changes ever failed to deserialize. But I am intimately familiar with the dynamic nature of software development, so I'm going to chock this one up to "an evolving ecosystem" and call it good 😁

Thank you again for taking the time to describe the issue in detail, and for working with Metaplex to further the standard. You and Omar are perfect examples of people working to advance the space, and I appreciate very much the time and energy you put in to advancing the "state of the art" for all of us ❤️

**Comment by samuelvanderwaal** [comment] 2022-04-25 23:22
Thanks for the kind words! I understand it can be a frustrating ecosystem sometimes but as you point out, it's a rapidly evolving.

On the subject of the creator changes, can you confirm if [#8060 ](https://solscan.io/token/DFR3KjTso6PFCyUtq48a2aPZQpMMoaFgtbdxtaLxF2TR#txs) had its creator array updated to go from multiple creators to a single one? I don't see the transaction in the explorer, but perhaps it's not showing for some reason.

**Comment by nonfungible-dev** [comment] 2022-04-26 00:50
Not frustrating at all! What I'm hearing is that there's a solution and all I need to do is wait a little bit 😁  All good news to me!

I should have clarified a bit with regard to creators, sorry about that! The first two in the the array have always been the same:

1. Candy Machine v1 address
2. The Snowball address (Pesky Penguins' deflationary mechanic)

The 3rd address in the creators array, the one that begins with `ppTeam`, used to be three different addresses. So we went from 5 creators in the array down to just 3, and this transition happened in the middle of November.

So to confirm: [Pesky Penguin #8060](https://solscan.io/token/DFR3KjTso6PFCyUtq48a2aPZQpMMoaFgtbdxtaLxF2TR#txs) was successfully updated (multiple times!), and I'm not sure why there wouldn't be any transactions associated with it, especially because I have always used metaboss to do the updates (though it likely would have been an earlier version we updated the creators array. I remember updating to version 0.3.0 at some point, but I forget what version I was coming _from_ because they were manual builds at the time).

Is it possible that the transaction "aged out" because it's more than 6 months old?

Let me know if there's anything else I can do. Otherwise, I will sit tight until the next version is out!

Thanks again 😁

**Comment by omarkilani** [comment] 2022-04-27 18:58
There are transactions associated with the metadata account of PP #8060.

These are the txns on the mint account:

```
[solana@rpc ~]$ solana-ledger-tool bigtable transaction-history DFR3KjTso6PFCyUtq48a2aPZQpMMoaFgtbdxtaLxF2TR
[2022-04-27T18:29:00.291631794Z INFO  solana_ledger_tool] solana-ledger-tool 1.9.18 (src:5d0f2a9f; feat:1070292356)
[2022-04-27T18:29:00.297959809Z INFO  solana_storage_bigtable::access_token] Requesting token for BigTableDataReadOnly scope
[2022-04-27T18:29:00.402840361Z INFO  solana_storage_bigtable::access_token] Token expires in 3599 seconds
MYtB36H59go1f3r3eEepjrSsN8tof1sHe2P1N4PuHgqnD7dMH7wvhzQ7oS7Eh4xSWcMtEo7ySyTSAwEtvieY9no
24SVc4EobPGp4e4dnbJ22MEG43FhdFqTtkDP19UR9rukx2nA59DV3aNYYVeT5hq2tC6mUAU7FRJyBy4aMYeAjawp
5UUJoHLj4n5v5HA7em6LCywHfzZkStESGUUzd4W8sjuydwegurkfcoBi6FMCA7wWNdb5kstzsFfJp7ct7s8UKpcc
```

These are the txns on the metadata account:

```
[solana@rpc ~]$ solana-ledger-tool bigtable transaction-history 5Sk1QwgfTgkNU2AKDJfg7bR2Q44T49EQgZddZCTmzhxw
[2022-04-27T18:30:01.841110109Z INFO  solana_ledger_tool] solana-ledger-tool 1.9.18 (src:5d0f2a9f; feat:1070292356)
[2022-04-27T18:30:01.847802250Z INFO  solana_storage_bigtable::access_token] Requesting token for BigTableDataReadOnly scope
[2022-04-27T18:30:01.948795989Z INFO  solana_storage_bigtable::access_token] Token expires in 3599 seconds
3UGHshAVhXWxvDU4fie5u8NZHqdjx5c3wCogpPavvwqwPRCEhBSXjZyTEBcbLecdwoVukDTrgUbcXoiwNfKtva4
4kaNABsCfo59kpvdcRLmzxpjCbGFMbLWiwF68FdAYPqQ3EL7NyHyfpNzxnfHsbKwyfyoWqwYz92AXAdEEmG7E4wW
5JYHC8nuhsMxJmbGSFseSbQB8g27E44pPMHxs8D3tqhbQENWGFyFCVCm2kHnEM8ztkjpDpN3WSD5UmNdVFTFx1pp
3MQfe3Q4yjRuyVgZ6GRC3opsFr63KMm5Zda7wTcsn3vfaTeLGyr4VyL8iNaTaWss6o8FLtWu7CxDyLJyj8V1wpMo
29mN8vHd1q4H82Xr7YqqJyEQs4fMMaKH32jxQAQSKTPzgVy2e3yhJ5G5zHmCurMqkHqZad2qaww2B9dL49hkYas9
5YhhaMzWgYSSKeYA4skQ8tzN4yDdk5NNa7yK4uLLCgzhXQYrHdUGJdbTJr1eNoyWxZ6TYbcAUnJxXMCP2DxovpsK
3fHPREtMkjBy2pt8MegLv9EjhYSLWbknkaky4pSpAwi6ik3YhaT59UT1o2HDJePUGUPV935pfUmN9fRzoavEeu8r
5UUJoHLj4n5v5HA7em6LCywHfzZkStESGUUzd4W8sjuydwegurkfcoBi6FMCA7wWNdb5kstzsFfJp7ct7s8UKpcc
```

`3UGH...` pushed this metadata:

```
2022/04/27 18:52:39.014513 solana.go:444: msgInst 0: program = metaplex, accounts = [5Sk1QwgfTgkNU2AKDJfg7bR2Q44T49EQgZddZCTmzhxw pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k], data = [1 1 32 0 0 0 80 101 115 107 121 32 80 101 110 103 117 105 110 115 32 35 56 48 54 48 0 0 0 0 0 0 0 0 0 0 0 0 10 0 0 0 78 79 79 84 0 0 0 0 0 0 63 0 0 0 104 116 116 112 115 58 47 47 97 114 119 101 97 118 101 46 110 101 116 47 72 122 79 110 102 78 77 87 81 66 72 84 57 118 48 68 87 56 69 114 57 89 70 119 100 105 71 74 88 52 45 117 75 57 82 83 89 65 82 56 102 120 69 244 1 1 3 0 0 0 135 35 134 27 83 153 173 73 166 213 73 13 254 1 156 113 34 24 205 42 233 242 137 173 173 195 214 108 110 42 89 229 1 0 12 25 250 103 242 3 129 143 173 110 204 157 11 1 247 211 138 199 219 79 142 183 195 96 206 63 208 102 152 127 62 43 1 40 12 63 245 233 144 127 205 69 77 225 56 60 107 184 84 240 194 136 55 121 217 128 246 223 140 64 40 122 145 17 203 60 0 60 0 0]
2022/04/27 18:52:39.014569 solana.go:775: serialized metadata(228): [32 0 0 0 80 101 115 107 121 32 80 101 110 103 117 105 110 115 32 35 56 48 54 48 0 0 0 0 0 0 0 0 0 0 0 0 10 0 0 0 78 79 79 84 0 0 0 0 0 0 63 0 0 0 104 116 116 112 115 58 47 47 97 114 119 101 97 118 101 46 110 101 116 47 72 122 79 110 102 78 77 87 81 66 72 84 57 118 48 68 87 56 69 114 57 89 70 119 100 105 71 74 88 52 45 117 75 57 82 83 89 65 82 56 102 120 69 244 1 1 3 0 0 0 135 35 134 27 83 153 173 73 166 213 73 13 254 1 156 113 34 24 205 42 233 242 137 173 173 195 214 108 110 42 89 229 1 0 12 25 250 103 242 3 129 143 173 110 204 157 11 1 247 211 138 199 219 79 142 183 195 96 206 63 208 102 152 127 62 43 1 40 12 63 245 233 144 127 205 69 77 225 56 60 107 184 84 240 194 136 55 121 217 128 246 223 140 64 40 122 145 17 203 60 0 60 0 0]
2022/04/27 18:52:39.014604 solana.go:779: metadata: {Name:Pesky Penguins #8060 Symbol:NOOT Uri:https://arweave.net/HzOnfNMWQBHT9v0DW8Er9YFwdiGJX4-uK9RSYAR8fxE SellerFeeBasisPoints:500 Creators:0xc00000eb58}
2022/04/27 18:52:39.014637 solana.go:780: metadata.Creators: &[{Address:A6XTVFiwGVsG6b6LsvQTGnV5LH3Pfa3qW3TGz8RjToLp Verified:true Share:0} {Address:pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k Verified:true Share:40} {Address:ppTeamTpw1cbC8ybJpppbnoL7xXD9froJNFb5uvoPvb Verified:false Share:60}]
```

What I don't really get is how the on-chain metadata would have been corrupted by this update as it looks well formed.

@samuelvanderwaal It's not clear which txn on the metadata account would have written past the V1 metadata object struct?

**Comment by omarkilani** [comment] 2022-04-28 01:51
There were 3 txns that called create_metadata_accounts or update_metadata_accounts:

`5UUJoHLj4n5v5HA7em6LCywHfzZkStESGUUzd4W8sjuydwegurkfcoBi6FMCA7wWNdb5kstzsFfJp7ct7s8UKpcc`
(October 09, 2021 22:46:00 PM +UTC)

```
2022/04/28 01:38:53.150507 solana.go:830: metadata: {Name:Pesky Penguins #8060 Symbol: Uri:https://arweave.net/lVY2EVJBChIZgqoAmwicQ5fQn1IqAAhqXD0D-tD_4B8 SellerFeeBasisPoints:500 Creators:0xc0006ceff0}
2022/04/28 01:38:53.150547 solana.go:831: metadata.Creators: &[{Address:A6XTVFiwGVsG6b6LsvQTGnV5LH3Pfa3qW3TGz8RjToLp Verified:true Share:0} {Address:pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k Verified:false Share:40} {Address:ppEnKM7amitqdTwp8pyngptp4hXdRrahbJZuvPxgtE4 Verified:false Share:20} {Address:3Z8ZvQxENYrgHX2o5AZt8MXUNEPVLL6MT3xqSc2XzX1L Verified:false Share:20} {Address:2pDZQCYKp9q6JQPWHDsFCoYE7odFp59jdtkt9e43cepX Verified:false Share:20}]
```

`5JYHC8nuhsMxJmbGSFseSbQB8g27E44pPMHxs8D3tqhbQENWGFyFCVCm2kHnEM8ztkjpDpN3WSD5UmNdVFTFx1pp`
(November 21, 2021 02:43:52 AM +UTC)

```
2022/04/28 01:43:13.068255 solana.go:444: msgInst 0: program = metaplex, accounts = [5Sk1QwgfTgkNU2AKDJfg7bR2Q44T49EQgZddZCTmzhxw pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k], data = [1 1 20 0 0 0 80 101 115 107 121 32 80 101 110 103 117 105 110 115 32 35 56 48 54 48 4 0 0 0 78 79 79 84 63 0 0 0 104 116 116 112 115 58 47 47 97 114 119 101 97 118 101 46 110 101 116 47 108 86 89 50 69 86 74 66 67 104 73 90 103 113 111 65 109 119 105 99 81 53 102 81 110 49 73 113 65 65 104 113 88 68 48 68 45 116 68 95 52 66 56 244 1 1 3 0 0 0 135 35 134 27 83 153 173 73 166 213 73 13 254 1 156 113 34 24 205 42 233 242 137 173 173 195 214 108 110 42 89 229 1 0 12 25 250 103 242 3 129 143 173 110 204 157 11 1 247 211 138 199 219 79 142 183 195 96 206 63 208 102 152 127 62 43 1 40 12 63 245 233 144 127 205 69 77 225 56 60 107 184 84 240 194 136 55 121 217 128 246 223 140 64 40 122 145 17 203 60 0 60 0 0]
2022/04/28 01:43:13.068328 solana.go:779: metadata: {Name:Pesky Penguins #8060 Symbol:NOOT Uri:https://arweave.net/lVY2EVJBChIZgqoAmwicQ5fQn1IqAAhqXD0D-tD_4B8 SellerFeeBasisPoints:500 Creators:0xc000541200}
2022/04/28 01:43:13.068351 solana.go:780: metadata.Creators: &[{Address:A6XTVFiwGVsG6b6LsvQTGnV5LH3Pfa3qW3TGz8RjToLp Verified:true Share:0} {Address:pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k Verified:true Share:40} {Address:ppTeamTpw1cbC8ybJpppbnoL7xXD9froJNFb5uvoPvb Verified:false Share:60}]
```

`3UGHshAVhXWxvDU4fie5u8NZHqdjx5c3wCogpPavvwqwPRCEhBSXjZyTEBcbLecdwoVukDTrgUbcXoiwNfKtva4`
(December 11, 2021 21:44:23 PM +UTC)

```
2022/04/28 01:44:52.608612 solana.go:444: msgInst 0: program = metaplex, accounts = [5Sk1QwgfTgkNU2AKDJfg7bR2Q44T49EQgZddZCTmzhxw pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k], data = [1 1 32 0 0 0 80 101 115 107 121 32 80 101 110 103 117 105 110 115 32 35 56 48 54 48 0 0 0 0 0 0 0 0 0 0 0 0 10 0 0 0 78 79 79 84 0 0 0 0 0 0 63 0 0 0 104 116 116 112 115 58 47 47 97 114 119 101 97 118 101 46 110 101 116 47 72 122 79 110 102 78 77 87 81 66 72 84 57 118 48 68 87 56 69 114 57 89 70 119 100 105 71 74 88 52 45 117 75 57 82 83 89 65 82 56 102 120 69 244 1 1 3 0 0 0 135 35 134 27 83 153 173 73 166 213 73 13 254 1 156 113 34 24 205 42 233 242 137 173 173 195 214 108 110 42 89 229 1 0 12 25 250 103 242 3 129 143 173 110 204 157 11 1 247 211 138 199 219 79 142 183 195 96 206 63 208 102 152 127 62 43 1 40 12 63 245 233 144 127 205 69 77 225 56 60 107 184 84 240 194 136 55 121 217 128 246 223 140 64 40 122 145 17 203 60 0 60 0 0]
2022/04/28 01:44:52.608680 solana.go:779: metadata: {Name:Pesky Penguins #8060 Symbol:NOOT Uri:https://arweave.net/HzOnfNMWQBHT9v0DW8Er9YFwdiGJX4-uK9RSYAR8fxE SellerFeeBasisPoints:500 Creators:0xc00000e888}
2022/04/28 01:44:52.608713 solana.go:780: metadata.Creators: &[{Address:A6XTVFiwGVsG6b6LsvQTGnV5LH3Pfa3qW3TGz8RjToLp Verified:true Share:0} {Address:pEsKYABNARLiDFYrjbjHDieD5h6gHrvYf9Vru62NX9k Verified:true Share:40} {Address:ppTeamTpw1cbC8ybJpppbnoL7xXD9froJNFb5uvoPvb Verified:false Share:60}]
```

The 2nd tx updated the creator array and shrunk it. I assume (?) the on-chain code just didn't zero fill past the end of the encoded data to the max length of the struct or something like that.

**Comment by samuelvanderwaal** [comment] 2022-04-28 06:20
Perhaps "corrupted" data is not the best description. If you create a NFT with a creators array with five creators you have a total data length of 561 bytes and the rest are zero filled (679 total). If you then update the creators array to have only three creators you're overwriting the array with 493 bytes of data but due the way borsh handles this and the way `token-metadata` is set up, that extra 68 bytes of data is still populated, just at the end of the array. So when we added the new metadata fields they overlapped with this extra data on some NFTs causing the valid to be deserialized incorrectly.

You can see our fix for this [here](https://github.com/metaplex-foundation/metaplex-program-library/pull/407). We create a new custom deserialization function to handle the invalid data at the end of the array and then we also now zero out the full byte array in the `update_metadata_accounts_v2` call which should fix any NFTs that have this extra data and prevent it from happening in the future.

**Comment by omarkilani** [comment] 2022-04-28 16:50
@samuelvanderwaal awesome. Thank you for the quick resolution!

**Comment by samuelvanderwaal** [comment] 2022-04-28 18:28
The updates to `token-metadata` should happen early next week and I plan to get Metaboss upgraded to use the `update_metadata_accounts_v2` by then so you'll be able to fix the Noot NFTs then.

**Comment by samuelvanderwaal** [comment] 2022-05-07 06:12
Following up on this, the fix is deployed to `mainnet` and I'm going to try to update metaboss this weekend to support `update_accounts_v2`.

**Comment by omarkilani** [comment] 2022-05-08 17:21
Awesome.

I have a version of metaboss that uses the v2 ix so we'll test with @nonfungible-dev

**Comment by omarkilani** [comment] 2022-05-09 00:57
@samuelvanderwaal can verify that a `collections set-and-verify` with metaboss is able to update the on-chain metadata:

https://explorer.solana.com/address/CH4X6QQfRTaAFm2kGnqJEPoQrfoHa1cP2jcPm4Z7rjF/metadata

The update tx is here:

https://explorer.solana.com/tx/43zLtCECuFrwVXab6LULZMR9KgHaJyeaLkq7RRVn3X8HQARSq9g1ZcD6BYrYrUdwbWxVzuZktruCiVcZCHewFFNR

And shows a:

```
> Program logged: "Corrupted metadata discovered: setting values to None"
```

Log message.

Thanks again!

**Comment by nonfungible-dev** [comment] 2022-05-09 01:21
I was just about to report in with our success, but it looks like Omar beat me to it!

Thanks everybody for resolving this issue so quickly! Appreciate the support and positive energy you bring to the space.

Please feel free to close this issue, and if there's any additional information or testing you'd like from me, please don't hesitate to reach out!

**Comment by samuelvanderwaal** [comment] 2022-05-09 23:39
Thanks for the patience and the feedback! Really good to see a successful report of the fix working.

**Closed by samuelvanderwaal** 2022-05-09 23:39 UTC
