### ISSUE TITLE
Issue burning NFT

### ISSUE THREAD

**Issue by ualdayan** [samuelvanderwaal/metaboss#187] opened 2022-09-23 21:31 UTC
I'm trying to use metaboss to burn a NFT, and I'm getting this as a result:

-32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-09-23T21:26:56.430615100Z DEBUG solana_client::nonblocking::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-09-23T21:26:56.431556200Z DEBUG solana_client::nonblocking::rpc_client]   2: Program log: Instruction: Burn NFT
[2022-09-23T21:26:56.432458600Z DEBUG solana_client::nonblocking::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/processor.rs:1722:19
[2022-09-23T21:26:56.433021900Z DEBUG solana_client::nonblocking::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 6557 of 200000 compute units
[2022-09-23T21:26:56.433721400Z DEBUG solana_client::nonblocking::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-09-23T21:26:56.434464600Z DEBUG solana_client::nonblocking::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete

It's an Orca NFT (balance is empty).  I noticed Orca leaves the SOL in the metadata account, so if I could burn the NFT in it's entirety I should see more SOL returned than if I just burn the token is my understanding.

**Comment by samuelvanderwaal** [comment] 2022-09-24 19:46
> I'm trying to use metaboss to burn a NFT, and I'm getting this as a result:
> 
> -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete [2022-09-23T21:26:56.430615100Z DEBUG solana_client::nonblocking::rpc_client] 1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1] [2022-09-23T21:26:56.431556200Z DEBUG solana_client::nonblocking::rpc_client] 2: Program log: Instruction: Burn NFT [2022-09-23T21:26:56.432458600Z DEBUG solana_client::nonblocking::rpc_client] 3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/processor.rs:1722:19 [2022-09-23T21:26:56.433021900Z DEBUG solana_client::nonblocking::rpc_client] 4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 6557 of 200000 compute units [2022-09-23T21:26:56.433721400Z DEBUG solana_client::nonblocking::rpc_client] 5: Program failed to complete: BPF program panicked [2022-09-23T21:26:56.434464600Z DEBUG solana_client::nonblocking::rpc_client] 6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
> 
> It's an Orca NFT (balance is empty). I noticed Orca leaves the SOL in the metadata account, so if I could burn the NFT in it's entirety I should see more SOL returned than if I just burn the token is my understanding.

This is a panic in the Token Metadata program, which is not great. Looks like it should check the length of the accounts passed in. Can you give me the NFT token address in Solscan or Solana Explorer so I can take a look?

**Comment by ualdayan** [comment] 2022-09-24 20:06
I think I may have an idea now why it did it - the token standard the metadata is set to is v1.  Does it need to be v1.3 in order for the full burn NFT transaction to work?  Orca sets update authority to itself (https://solscan.io/account/3axbTs2z5GBy6usVbNVoqEgZMng3vZvMnAoX29BFfwhr ) so you can see how many unique NFTs get minted each day.  That's a lot of SOL getting locked up seemingly for good every day unfortunately.

**Comment by samuelvanderwaal** [comment] 2022-09-24 23:54
> I think I may have an idea now why it did it - the token standard the metadata is set to is v1. Does it need to be v1.3 in order for the full burn NFT transaction to work? Orca sets update authority to itself (https://solscan.io/account/3axbTs2z5GBy6usVbNVoqEgZMng3vZvMnAoX29BFfwhr ) so you can see how many unique NFTs get minted each day. That's a lot of SOL getting locked up seemingly for good every day unfortunately.

The issue is these are not NFTs (Token Standard 0 or 3), they are Fungible Assets (Token Standard 1), so they can't be burned with this instruction. There's no handler on Token Metadata currently for closing metadata accounts for Fungible Assets, unfortunately.

**Closed** 2022-09-26 17:06 UTC
